### ISSUE TITLE
HDMI视频采集性能如何提高?

### ISSUE THREAD

**Issue by vincentzz** [Jackadminx/KVM-Card-Mini#8]
大佬你好，我在用v2.6版本硬件，原版Client以及增强Client里最多都只能选1080P，而且目测帧率远远达不到60，色深不足，同时MS2109发热严重。

我被控机MacBook输出信号是2K 60hz，主控机Windows用的4K 144hz屏幕，所以从主控机上看到的画面就比较难以接受。
我想请问是散热局限了性能吗？还是被芯片本身的性能限制了？

如果想高质量采集视频，可以通过改固件外加风扇实现吗？还是说需要更强的芯片才行？

**Comment by Jackadminx** [comment]
MS2109最大只支持1080P30帧率的视频输出，如果需要更好的画质和帧率可以使用其他的采集卡如MS2130，Client支持使用非板载的采集卡。MS2109发热是正常现象，可以通过安装散热片解决。

**Comment by vincentzz** [comment]
明白了，多谢大佬指点
